### PR TITLE
Ensure pyprismatic build string contains python version

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@scopatz @chrisburr 

In this PR I modified the build string of the pyprismatic subpackage to ensure it would include the python version it was built against, which also seems to trigger builds against both python 3.6 and 3.7, which is a nice side-effect. This seems to work until it reaches the testing stage where it tries to test the 2.7 build, even though that has been skipped. Any thoughts on why this is happening?

Thanks in advance!

**Comment by douglowe** [comment]
hi @tschoonj - the change seems sensible to me, the side effects are unexpected by me too (but I am still trying to get used to the conda-forge system...). I'll look in detail at the build log tomorrow morning, but perhaps this change is causing the over-arching package (prismatic) to trigger builds for all python versions. Maybe we should be adding an exclusion for py2k to that package too?

**Comment by tschoonj** [comment]
Thanks for the suggestion @douglowe , that seems to have fixed it.

If you're ok with this, feel free to merge it in: this PR ensures that we now have separate builds for python 3.6 and 3.7.

Tomorrow I will add some more fixes, in new PRs

**Comment by tschoonj** [comment]
So everybody fine with merging this PR in?

**Comment by douglowe** [comment]
I’ve not yet had a chance to look properly at this (sorry, busy with teaching & xmas meals this week). Could I look at this tomorrow (Friday), and get back to you then?

**Comment by tschoonj** [comment]
Sure no problem.

**Comment by tschoonj** [comment]
How do you know that only the last version to be built will remain? You're referring to the pyprismatic package?

**Comment by douglowe** [comment]
I built the packages locally, and checked the index.json file in the prismatic package. This is what it contained:
  "depends": [
    "prismatic_cli 1.2.1 cpu_h4afe770_1",
    "prismatic_gui 1.2.1 cpu_hc9b8b49_1",
    "pyprismatic 1.2.1 py37_cpu_hc9b8b49_1"
  ],
Of the 2 pyprismatic packages that were built (in this case) it was the py3.7 which was built last (so the prismatic package which would have depended on the 3.6 build had been overwritten).

**Comment by douglowe** [comment]
BTW - apologies for editing the file directly - I was trying to work out how to easily submit a pull request for this, but evidently failed to manage that :-/

**Comment by tschoonj** [comment]
> BTW - apologies for editing the file directly - I was trying to work out how to easily submit a pull request for this, but evidently failed to manage that :-/

No worries, this is perfectly fine

**Comment by douglowe** [comment]
Hmm, that claims it worked, and the pyprismatic and cli/gui packages look fine, but the prismatic packages it made are:
prismatic-1.2.1-py37_cpu_h5baa593_1.tar.bz2
prismatic-1.2.1-1.tar.bz2

I'll tidy up the selectors & try again, see if this is a one off fault.

**Comment by douglowe** [comment]
Okay - this seems to be related to build order (so is random), as now the py36 package seems to be the one that has been named properly:
prismatic-1.2.1-py36_cpu_h5baa593_1.tar.bz2
prismatic-1.2.1-1.tar.bz2

I will try a local build - see if I can replicate the problem (and then what the package contents are).

**Comment by douglowe** [comment]
@ericpre & @tschoonj,

I managed to work out what was going on with the prismatic subpackage build:
1) the subpackage was being built for python 2.7 (which I'd not accounted for in the build string creation, hence the empty string)
2) the subpackage was, randomly and for a still unknown reason, not being built for both python 3.6 and python 3.7.

I've explicitly excluded python 2 builds for this subpackage, and added python to the host requirements, and I think that the combination of these two changes has now fixed the problem.

**Review by douglowe — APPROVED** [review]
I've tested the changes locally now too & think this is ready for merging.

**Pull request merged**
