### PR TITLE
Fix my listing as maintainer

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@douglowe Something went wrong when you added me as a maintainer, probably because you used origin/master directly instead of a fork and pull-request, resulting in me not being listed in the README.md and codeowners file. This PR addresses this.

**Review by douglowe — APPROVED** [review]
Ahh, that will teach me to just follow the first advice on doing something I find in google.

**Comment by douglowe** [comment]
Thanks for the correction - I'll merge it now.

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
